import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

import connectMongo from "../utils/connectMongo";
import Test from "../models/testModel";

export default function Home({ tests }) {
  const createTest = async () => {
    const randomNum = Math.floor(Math.random() * 1000);
    const res = await fetch("/api/test/add", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        name: `Test ${randomNum}`,
        email: `test${randomNum}@test.com`,
      }),
    });
    const data = await res.json();
    console.log(data);
  };

  return (
    <div classNameName={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="m-10 p-10">
        <button onClick={createTest}>CreateTest</button>
      </main>

      <div className="">
        {tests.map((test) => (
          <a href="" key={test._id} className="border-2">
            <h2>{test.name} &rarr;</h2>
            <p>{test.email}</p>
          </a>
        ))}
      </div>
    </div>
  );
}

export const getServerSideProps = async () => {
  try {
    console.log("connecting to mongo");
    await connectMongo();
    console.log("connected to mongo");

    console.log("fetching a document");
    const tests = await Test.find();
    console.log("fetchedd document");
    return {
      props: {
        tests: JSON.parse(JSON.stringify(tests)),
      },
    };
  } catch (error) {
    console.log(error);
    return {
      notFound: true,
    };
  }
};
